server.port=4040
spring.application.name=IETScroll
server.admin.email=${ADMIN_EMAIL}
server.address=0.0.0.0

#Database
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#AI for resume checking
spring.ai.openai.api-key=${Nvidia_AI_Key}
spring.ai.openai.base-url=https://integrate.api.nvidia.com
#I am using this model, Link : https://build.nvidia.com/google/gemma-2-2b-it
spring.ai.openai.chat.options.model=mistralai/mistral-small-4-119b-2603

#JWT
jwt.secret=${JWT_SECRET}

#Email
SENDGRID_API_KEY=${SENDGRID_API_KEY}

#Images
cloudinary.cloud-name = ${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key = ${CLOUDINARY_API_KEY}
cloudinary.api-secret = ${CLOUDINARY_API_SECRET}

#Verification of image
sightengine.api-user = ${SIGHTENGINE_API_USER}
sightengine.api-secret = ${SIGHTENGINE_API_SECRET}
sightengine.api-url=https://api.sightengine.com/1.0/check.json
