package com.ietscroll.entity;

public enum Branch {
	COMPUTER_SCIENCE_AND_BUISNESS_SYSTEM,
	COMPUTER_SCIENCE,
	INFORMATION_TECHNOLOGY,
	ELECTRONICS_AND_TELECOMMUNICATION_ENGINEERING,
	ELECTRONICS_AND_INSTRUMENTATION_ENGINEERING,
	MECHANICAL_ENGINEERING,
	CIVIL_ENGINEERING,
	OTHER
}
